<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5e46c084f2d4d',
		'title' => 'Cupones',
		'fields' => array(
			array(
				'key' => 'field_5e46c0a417f58',
				'label' => 'Código cupon',
				'name' => 'codigo_cupon',
				'type' => 'text',
				'instructions' => 'Ingrese el código del cupón',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e46c10617f59',
				'label' => 'Plan Pertenece',
				'name' => 'plan_pertenece',
				'type' => 'relationship',
				'instructions' => 'Ingrese los planes a los que pertenece el cupón',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'plan',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
			array(
				'key' => 'field_5e46c1a317f5a',
				'label' => 'Valido desde',
				'name' => 'valido_desde',
				'type' => 'date_picker',
				'instructions' => 'Ingrese la fecha desde la que es valido el cupón',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e46c10617f59',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'F j, Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5e46c23217f5b',
				'label' => 'Valido hasta',
				'name' => 'valido_hasta',
				'type' => 'date_picker',
				'instructions' => 'Ingrese la fecha hasta la que es valida el cupón',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e46c1a317f5a',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'F j, Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5e46c28617f5c',
				'label' => 'Oferta',
				'name' => 'oferta',
				'type' => 'text',
				'instructions' => 'Ingrese la descripción corta de la oferta del cupón.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e46c10617f59',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e46c2eb17f5d',
				'label' => 'Tipo de contrato',
				'name' => 'tipo_de_contrato',
				'type' => 'button_group',
				'instructions' => 'Seleccione el tipo de contrato de validez para el cupón',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e46c10617f59',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => get_option('type_plan__'),
				'allow_null' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5e46c40b738c1',
				'label' => 'Valor Descuento',
				'name' => 'valor_descuento',
				'type' => 'text',
				'instructions' => 'Porcentaje de descuento',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e46c28617f5c',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e501536805c7',
				'label' => 'Descripcion cupon y proveedor',
				'name' => 'descripcion_cupon_y_proveedor',
				'type' => 'text',
				'instructions' => 'Ingrese la descripción corta del cupón y su proveedor',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e46c0a417f58',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'cupon',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5a42bf8dcaa8d',
		'title' => 'Options',
		'fields' => array(
			array(
				'key' => 'field_5a42bfc085d64',
				'label' => 'Featured posts',
				'name' => 'featured_posts',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'post',
				),
				'taxonomy' => array(
				),
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_5a42bfae8ee5d',
				'label' => 'Custom CSS',
				'name' => 'custom_css',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'modified' => 1516930487,
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5e4424f4be605',
		'title' => 'Paises',
		'fields' => array(
			array(
				'key' => 'field_5e442523fede5',
				'label' => 'extension de pais',
				'name' => 'extension_de_pais',
				'type' => 'text',
				'instructions' => 'Ingrese el shortname ó extensión de dominio del pais',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 3,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'pais',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5e443044493b6',
		'title' => 'Planes',
		'fields' => array(
			array(
				'key' => 'field_5e44304fb1f7f',
				'label' => 'Proveedor_pertenece',
				'name' => 'proveedor_pertenece',
				'type' => 'relationship',
				'instructions' => 'Seleccione el Proveedor al que pertenece este plan',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'proveedor',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
			array(
				'key' => 'field_5e4431e2d9151',
				'label' => 'Tipos de Hosting validos',
				'name' => 'tipos_de_hosting_validos',
				'type' => 'taxonomy',
				'instructions' => 'Seleccione los tipos de hosting para los que este plan esta disponible',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'tipo',
				'field_type' => 'checkbox',
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
				'allow_null' => 0,
			),
			array(
				'key' => 'field_5e45743b9deed',
				'label' => 'Precio',
				'name' => 'precio',
				'type' => 'text',
				'instructions' => 'Ingrese el precio del Plan',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e458052ba993',
				'label' => 'Caracteristicas',
				'name' => 'caracteristicas',
				'type' => 'textarea',
				'instructions' => 'Insertar las características separadas por coma. Una característica por linea.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 12,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5e458254ba994',
				'label' => 'Tipo de Plan',
				'name' => 'tipo_de_plan',
				'type' => 'button_group',
				'instructions' => 'Selecciona el tipo de Plan',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'mensual' => 'Mensual',
					'anual' => 'Anual',
				),
				'allow_null' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5e4db681a362c',
				'label' => 'shortname_plan',
				'name' => 'shortname_plan',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e44304fb1f7f',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'plan',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5b1541ff2987a',
		'title' => 'Preguntas Frecuentes',
		'fields' => array(
			array(
				'key' => 'field_5b154226f58d0',
				'label' => 'Preguntas frecuentes',
				'name' => 'faqs',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5b154252f58d1',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Nueva pregunta',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'faqs',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'modified' => 1528122362,
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5a42bf578dca1',
		'title' => 'Proveedores',
		'fields' => array(
			array(
				'key' => 'field_5a41578760672',
				'label' => 'General',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a8dd5ef83cf3',
				'label' => 'Países disponibles',
				'name' => 'pais',
				'type' => 'relationship',
				'instructions' => 'Elija los países en los cuales esta disponible el servicio de este proveedor.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'pais',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
			array(
				'key' => 'field_5a7df5a85b2e0',
				'label' => 'Sede',
				'name' => 'sede',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a4958b7166a4',
				'label' => 'Año de fundación',
				'name' => 'fundado',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a414d6c0a850',
				'label' => 'Logo',
				'name' => 'logo',
				'type' => 'image',
				'instructions' => 'Sube un logo en formato cuadrado de dimensiones 115 x 155 px.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_8a414d6c0a101',
				'label' => 'Imagen de contenido',
				'name' => 'imagen_contenido',
				'type' => 'image',
				'instructions' => 'Sube una imagen para colocar entre el texto en formato png ó svg de dimensiones 473 x 272 px.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5a414d6c0a757',
				'label' => 'Single Banner',
				'name' => 'singlebanner',
				'type' => 'image',
				'instructions' => 'Sube un banner en formato svg rectangular.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6a414d6c0a751',
				'label' => 'Image carousel 1',
				'name' => 'img_carousel1',
				'type' => 'image',
				'instructions' => 'Sube una imagen (png) para el carrusel en dimensiones 464x236',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6a414d6c0a752',
				'label' => 'Image carousel 2',
				'name' => 'img_carousel2',
				'type' => 'image',
				'instructions' => 'Sube una imagen (png) para el carrusel en dimensiones 464x236',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6a414d6c0a753',
				'label' => 'Image carousel 3',
				'name' => 'img_carousel3',
				'type' => 'image',
				'instructions' => 'Sube una imagen (png) para el carrusel en dimensiones 464x236',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6a414d6c0a754',
				'label' => 'Image carousel 4',
				'name' => 'img_carousel4',
				'type' => 'image',
				'instructions' => 'Sube una imagen (png) para el carrusel en dimensiones 464x236',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6a414d6c0a755',
				'label' => 'Image carousel 5',
				'name' => 'img_carousel5',
				'type' => 'image',
				'instructions' => 'Sube una imagen (png) para el carrusel en dimensiones 464x236',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6a414d6c0a756',
				'label' => 'Image carousel 6',
				'name' => 'img_carousel6',
				'type' => 'image',
				'instructions' => 'Sube una imagen (png) para el carrusel en dimensiones 464x236',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5ad1ec8e09e0a',
				'label' => 'Header',
				'name' => 'header',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'jpg,png,jpeg',
			),
			array(
				'key' => 'field_5a73682a61074',
				'label' => 'Atención al cliente',
				'name' => 'soporte',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => get_option('customer_supports_vyg'),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5a41501431d14',
				'label' => 'Resumen de la empresa',
				'name' => 'resumen',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_5a425746169b6',
				'label' => 'Resumen de características',
				'name' => 'resumen_caracteristicas',
				'type' => 'text',
				'instructions' => 'Inserte las características principales de este proveedor separadas por comas.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5b08219aeac92',
				'label' => 'Etiqueta',
				'name' => 'etiqueta',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'recommended' => 'Recomendado',
					'featured' => 'Destacado',
					'bestvalue' => 'Mejor Valor',
					'offer' => 'En oferta!',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a415715a39ca',
				'label' => 'Precios',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a4273b9c0455',
				'label' => 'Métodos de pago',
				'name' => 'metodos_pago',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => get_option('payment_methods_vyg'),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5a4157d150f7d',
				'label' => 'Planes',
				'name' => 'planes',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5a4157e450f7e',
						'label' => 'Plan',
						'name' => 'plan_titulo',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5a41583f50f80',
						'label' => 'Producto',
						'name' => 'plan_producto',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'tipo',
						'field_type' => 'select',
						'allow_null' => 0,
						'return_format' => 'object',
						'multiple' => 0,
						'add_term' => 1,
						'load_terms' => 0,
						'save_terms' => 0,
					),
					array(
						'key' => 'field_5a8b2c3ac76f5',
						'label' => 'Moneda',
						'name' => 'plan_moneda',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'VEF' => 'Bolívares (Venezuela)',
							'BOB' => 'Boliviano',
							'BRL' => 'Real Brasileño',
							'CRC' => 'Colón (Costa Rica)',
							'USD' => 'Dólar Estadounidense',
							'EUR' => 'Euro',
							'ARS' => 'Peso Argentino',
							'CLP' => 'Peso Chileno',
							'COP' => 'Peso Colombiano',
							'MXN' => 'Peso Mexicano',
							'UYU' => 'Peso Uruguayo',
							'PEN' => 'Sol (Perú)',
						),
						'default_value' => array(
							0 => 'USD',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5a41580950f7f',
						'label' => 'Precio',
						'name' => 'plan_precio',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5a42f7af77b06',
				'label' => 'Otros',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a42f5c777b03',
				'label' => 'Centros de datos',
				'name' => 'datacenters',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5a42f5ed77b04',
						'label' => 'Ciudad/Estado',
						'name' => 'datacenter_ciudad',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5a42f72277b05',
						'label' => 'Pais',
						'name' => 'datacenter_pais',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'arg' => 'Argentina',
							'bra' => 'Brasil',
							'eng' => 'Inglaterra',
							'nld' => 'Países Bajos',
							'ita' => 'Italia',
							'sgp' => 'Singapur',
							'uru' => 'Uruguay',
							'usa' => 'Estados Unidos',
						),
						'default_value' => array(
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'array',
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_5a4682a595b19',
				'label' => 'Características',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a4682bf95b1a',
				'label' => 'Garantía',
				'name' => 'garantia',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No ofrece',
					7 => '7 días',
					15 => '15 días',
					30 => '30 días',
					60 => '60 días',
				),
				'default_value' => array(
					0 => 'no',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a46853dc2e1e',
				'label' => 'Dominio',
				'name' => 'dominio',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No incluído',
					'anual' => 'Incluido (plan anual)',
					'gratis' => 'Gratis',
				),
				'default_value' => array(
					0 => 'no',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5aba257cb1aee',
				'label' => 'Certificado SSL',
				'name' => 'ssl',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No incluído',
					'letsencrypt' => 'Gratis (Let\'s Encrypt)',
					'pago' => 'De pago',
				),
				'default_value' => array(
					0 => 'no',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a49554e6ba6b',
				'label' => 'Contacto',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a7df634df186',
				'label' => 'Sitio Web',
				'name' => 'url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a49557e6ba6c',
				'label' => 'Facebook',
				'name' => 'social_facebook',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a4955e06ba6d',
				'label' => 'Twitter',
				'name' => 'social_twitter',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a4955ef6ba6e',
				'label' => 'LinkedIn',
				'name' => 'social_linkedin',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a4956036ba6f',
				'label' => 'Google+',
				'name' => 'social_google',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a4956196ba70',
				'label' => 'YouTube',
				'name' => 'social_youtube',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5abd18b63218d',
				'label' => 'Ratings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5abd1dc5d9a9f',
				'label' => 'Opiniones (total)',
				'name' => 'total_opiniones',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5abd192a3218e',
				'label' => 'Atención al cliente (total)',
				'name' => 'total_soporte',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5abd194b3218f',
				'label' => 'Facilidad de uso (total)',
				'name' => 'total_usabilidad',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5abd1d4f32190',
				'label' => 'Funcionalidades (total)',
				'name' => 'total_funcionalidades',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5abd1d7f32191',
				'label' => 'Valor/precio (total)',
				'name' => 'total_valor',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5abd1d9132192',
				'label' => 'Confiabilidad (total)',
				'name' => 'total_confiabilidad',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5b06c70b6d6d8',
				'label' => 'Links de afiliados',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a415260df139',
				'label' => 'General',
				'name' => 'url_afiliado',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b06ca946d6da',
				'label' => 'Links locales',
				'name' => 'url_afiliado_local',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5b06caba6d6db',
						'label' => 'País',
						'name' => 'pais',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'argentina' => 'Argentina',
							'bolivia' => 'Bolivia',
							'brasil' => 'Brasil',
							'chile' => 'Chile',
							'colombia' => 'Colombia',
							'costa-rica' => 'Costa Rica',
							'ecuador' => 'Ecuador',
							'el-salvador' => 'El Salvador',
							'espana' => 'España',
							'estados-unidos' => 'Estados Unidos',
							'guatemala' => 'Guatemala',
							'guinea-ecuatorial' => 'Guinea Ecuatorial',
							'honduras' => 'Honduras',
							'mexico' => 'México',
							'nicaragua' => 'Nicaragua',
							'panama' => 'Panama',
							'paraguay' => 'Paraguay',
							'peru' => 'Perú',
							'puerto-rico' => 'Puerto Rico',
							'republica-dominicana' => 'República Dominicana',
							'uruguay' => 'Uruguay',
							'venezuela' => 'Venezuela',
						),
						'default_value' => array(
						),
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b06cbb56d6dc',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_5e4c0bb3143fe',
				'label' => 'Dominios No Disponibles',
				'name' => 'dominios_no_disponibles',
				'type' => 'text',
				'instructions' => 'Ingrese los dominios no permitidos por este proveedor, separados por una coma.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'proveedor',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5a6aaa64154e7',
		'title' => 'Reviews',
		'fields' => array(
			array(
				'key' => 'field_5a7effb57ccfc',
				'label' => 'Proveedor',
				'name' => 'proveedor',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'proveedor',
				),
				'taxonomy' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_5a7efadf19534',
				'label' => 'Nombre y apellido',
				'name' => 'nombre',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a96fa48d135e',
				'label' => 'Avatar',
				'name' => 'avatar',
				'type' => 'image',
				'instructions' => 'Carga una imagen en formato JPG o PNG de tamaño máximo 150 x 150 pixeles.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
				'min_width' => 50,
				'min_height' => 50,
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => 1,
				'mime_types' => 'jpg,jpeg,png',
			),
			array(
				'key' => 'field_5a7efc2597399',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a7efa701952f',
				'label' => 'Atención al cliente',
				'name' => 'puntuacion_soporte',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 5,
				'step' => '',
			),
			array(
				'key' => 'field_5a7efa8b19530',
				'label' => 'Facilidad de uso',
				'name' => 'puntuacion_usabilidad',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 5,
				'step' => '',
			),
			array(
				'key' => 'field_5a7efaa419531',
				'label' => 'Funcionalidades',
				'name' => 'puntuacion_funcionalidades',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 5,
				'step' => '',
			),
			array(
				'key' => 'field_5a7efab519532',
				'label' => 'Valor/precio',
				'name' => 'puntuacion_valor',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 5,
				'step' => '',
			),
			array(
				'key' => 'field_5a7efacd19533',
				'label' => 'Confiabilidad',
				'name' => 'puntuacion_confiabilidad',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 5,
				'step' => '',
			),
			array(
				'key' => 'field_5a7efb5219538',
				'label' => 'Pais',
				'name' => 'pais',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'argentina' => 'Argentina',
					'bolivia' => 'Bolivia',
					'chile' => 'Chile',
					'colombia' => 'Colombia',
					'costa-rica' => 'Costa Rica',
					'ecuador' => 'Ecuador',
					'el-salvador' => 'El Salvador',
					'espana' => 'España',
					'estados-unidos' => 'Estados Unidos',
					'guatemala' => 'Guatemala',
					'guinea-ecuatorial' => 'Guinea Ecuatorial',
					'honduras' => 'Honduras',
					'mexico' => 'Mexico',
					'nicaragua' => 'Nicaragua',
					'panama' => 'Panama',
					'paraguay' => 'Paraguay',
					'peru' => 'Peru',
					'puerto-rico' => 'Puerto Rico',
					'republica-dominicana' => 'Republica Dominicana',
					'uruguay' => 'Uruguay',
					'venezuela' => 'Venezuela',
					'otro' => 'Otro',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a7efb4219537',
				'label' => 'Hosting previo',
				'name' => 'hosting_previo',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'ninguno' => 'Ninguno',
					'godaddy' => 'GoDaddy',
					'site5' => 'Site5',
					'bluehost' => 'Bluehost',
					'otro' => 'Otro',
				),
				'default_value' => array(
					0 => 'ninguno',
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a7efb7219539',
				'label' => 'Servicio usado',
				'name' => 'servicio_contratado',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'tipo',
				'field_type' => 'select',
				'allow_null' => 0,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5a7efbab1953a',
				'label' => 'Tipo de web',
				'name' => 'tipo_web',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'corporativo' => 'Web corporativa',
					'portfolio' => 'Portfolio',
					'ecommerce' => 'Tienda online',
					'wordpress' => 'Blog WordPress',
					'webapp' => 'Web app',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a96faf8c9953',
				'label' => 'Sitio web',
				'name' => 'url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a7efb1419536',
				'label' => 'Fuente',
				'name' => 'fuente',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'organico' => 'Orgánico',
					'traduccion' => 'Traducida',
					'facebook' => 'Facebook',
					'google' => 'Google',
					'twitter' => 'Twitter',
					'yelp' => 'Yelp',
					'otro' => 'Otro',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'opiniones',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'modified' => 1522433555,
	));
	
	endif;
?>